stages:
# - stage: Build
#   displayName: Build stage
#   jobs:  
#   - job: Build
#     displayName: Build job
#     pool: niadak
#     steps:
#     - script: echo Hello, world!
#       displayName: 'Run a one-line script'

#     - script: |
#         echo Add other tasks to build, test, and deploy your project.
#         echo See https://aka.ms/yaml
#       displayName: 'Run a multi-line script'


jobs:  
- deployment: VMDeploy
  displayName: Deploy to VM job
  environment: Env1
  pool: default
  strategy:
    rolling:
      maxBatchSize: 2
      deploy:
        steps:
          - script: echo Hello, world! This is deploy job
            displayName: 'Run a one-line script'